version: "3"
services:
 zookeeper:
  image: "bitnami/zookeeper:latest"
  ports:
   - "2181:2181"
  environment:
    - ZOO_ENABLE_AUTH=yes
    - ZOO_SERVER_USERS=kafka
    - ZOO_SERVER_PASSWORDS=kafka_password
 kafka-1:
  image: "bitnami/kafka:latest"
  hostname: kafka-1
  environment:
   - ALLOW_ANONYMOUS_LOGIN=yes
   - KAFKA_ENABLE_KRAFT=yes
   - KAFKA_CFG_PROCESS_ROLES=broker,controller
   - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
   #- KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
   - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
   - KAFKA_BROKER_ID=1
   - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
   - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
   - ALLOW_PLAINTEXT_LISTENER=yes
   #- KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092,CLIENT://kafka:9092,EXTERNAL://localhost:9093
   #- KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
   - BITNAMI_DEBUG=yes
   - KAFKA_KRAFT_CLUSTER_ID=OTMwNzFhYTY1ODNiNGE5OT
   - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
   - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
  ports:
   - "9092:9092"
   - "9093:9093"
#  depends_on:
#   - zookeeper
 kafka-2:
   image: "bitnami/kafka:latest"
   hostname: kafka-2
   environment:
     - ALLOW_ANONYMOUS_LOGIN=yes
     - KAFKA_ENABLE_KRAFT=yes
     - KAFKA_CFG_PROCESS_ROLES=broker,controller
     - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
     #- KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
     - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
     - KAFKA_BROKER_ID=2
     - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
     - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
     - ALLOW_PLAINTEXT_LISTENER=yes
     #- KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092,CLIENT://kafka:9092,EXTERNAL://localhost:9093
     #- KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
     - BITNAMI_DEBUG=yes
     - KAFKA_KRAFT_CLUSTER_ID=OTMwNzFhYTY1ODNiNGE5OT
     - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
     - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
   ports:
     - "9094:9092"
     - "9095:9093"
#   depends_on:
#     - zookeeper
 kafka-3:
   image: "bitnami/kafka:latest"
   hostname: kafka-3
   environment:
     - ALLOW_ANONYMOUS_LOGIN=yes
     - KAFKA_ENABLE_KRAFT=yes
     - KAFKA_CFG_PROCESS_ROLES=broker,controller
     - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
     #- KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
     - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
     - KAFKA_BROKER_ID=3
     - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
     - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
     - ALLOW_PLAINTEXT_LISTENER=yes
     #- KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092,CLIENT://kafka:9092,EXTERNAL://localhost:9093
     #- KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
     - BITNAMI_DEBUG=yes
     - KAFKA_KRAFT_CLUSTER_ID=OTMwNzFhYTY1ODNiNGE5OT
     - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
     - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
   ports:
     - "9096:9092"
     - "9097:9093"
   #depends_on:
   #  - zookeeper

